/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DirectoryPickerField: typeof import('./../components/DirectoryPickerField.vue')['default']
    PageLayout: typeof import('./../components/PageLayout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensitiveImage: typeof import('./../components/SensitiveImage.vue')['default']
    SideMenu: typeof import('./../components/menu/SideMenu.vue')['default']
    SideMenuNode: typeof import('./../components/menu/SideMenuNode.vue')['default']
    SubPageLayout: typeof import('./../components/PageLayout/SubPageLayout.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTagInput: typeof import('tdesign-vue-next')['TagInput']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    TTransfer: typeof import('tdesign-vue-next')['Transfer']
  }
}

// For TSX support
declare global {
  const DirectoryPickerField: typeof import('./../components/DirectoryPickerField.vue')['default']
  const PageLayout: typeof import('./../components/PageLayout/PageLayout.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SensitiveImage: typeof import('./../components/SensitiveImage.vue')['default']
  const SideMenu: typeof import('./../components/menu/SideMenu.vue')['default']
  const SideMenuNode: typeof import('./../components/menu/SideMenuNode.vue')['default']
  const SubPageLayout: typeof import('./../components/PageLayout/SubPageLayout.vue')['default']
  const TAlert: typeof import('tdesign-vue-next')['Alert']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
  const TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDivider: typeof import('tdesign-vue-next')['Divider']
  const TDropdown: typeof import('tdesign-vue-next')['Dropdown']
  const TEmpty: typeof import('tdesign-vue-next')['Empty']
  const TImage: typeof import('tdesign-vue-next')['Image']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TList: typeof import('tdesign-vue-next')['List']
  const TListItem: typeof import('tdesign-vue-next')['ListItem']
  const TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
  const TLoading: typeof import('tdesign-vue-next')['Loading']
  const TPagination: typeof import('tdesign-vue-next')['Pagination']
  const TProgress: typeof import('tdesign-vue-next')['Progress']
  const TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
  const TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
  const TSelect: typeof import('tdesign-vue-next')['Select']
  const TSwitch: typeof import('tdesign-vue-next')['Switch']
  const TTable: typeof import('tdesign-vue-next')['Table']
  const TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
  const TTabs: typeof import('tdesign-vue-next')['Tabs']
  const TTag: typeof import('tdesign-vue-next')['Tag']
  const TTagInput: typeof import('tdesign-vue-next')['TagInput']
  const TTextarea: typeof import('tdesign-vue-next')['Textarea']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  const TTransfer: typeof import('tdesign-vue-next')['Transfer']
}