/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PageLayout: typeof import('./../components/PageLayout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./../components/menu/SideMenu.vue')['default']
    SideMenuNode: typeof import('./../components/menu/SideMenuNode.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}

// For TSX support
declare global {
  const PageLayout: typeof import('./../components/PageLayout/PageLayout.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SideMenu: typeof import('./../components/menu/SideMenu.vue')['default']
  const SideMenuNode: typeof import('./../components/menu/SideMenuNode.vue')['default']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDropdown: typeof import('tdesign-vue-next')['Dropdown']
  const TEmpty: typeof import('tdesign-vue-next')['Empty']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TList: typeof import('tdesign-vue-next')['List']
  const TListItem: typeof import('tdesign-vue-next')['ListItem']
  const TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
  const TPagination: typeof import('tdesign-vue-next')['Pagination']
  const TSelect: typeof import('tdesign-vue-next')['Select']
  const TSwitch: typeof import('tdesign-vue-next')['Switch']
  const TTable: typeof import('tdesign-vue-next')['Table']
  const TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
  const TTabs: typeof import('tdesign-vue-next')['Tabs']
  const TTag: typeof import('tdesign-vue-next')['Tag']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
}