/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DirectoryPickerField: typeof import('./src/components/DirectoryPickerField.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensitiveImage: typeof import('./src/components/SensitiveImage.vue')['default']
    SideMenu: typeof import('./src/components/menu/SideMenu.vue')['default']
    SideMenuNode: typeof import('./src/components/menu/SideMenuNode.vue')['default']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    TTransfer: typeof import('tdesign-vue-next')['Transfer']
  }
}

// For TSX support
declare global {
  const DirectoryPickerField: typeof import('./src/components/DirectoryPickerField.vue')['default']
  const PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SensitiveImage: typeof import('./src/components/SensitiveImage.vue')['default']
  const SideMenu: typeof import('./src/components/menu/SideMenu.vue')['default']
  const SideMenuNode: typeof import('./src/components/menu/SideMenuNode.vue')['default']
  const SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
  const TAlert: typeof import('tdesign-vue-next')['Alert']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
  const TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDivider: typeof import('tdesign-vue-next')['Divider']
  const TEmpty: typeof import('tdesign-vue-next')['Empty']
  const TImage: typeof import('tdesign-vue-next')['Image']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TLoading: typeof import('tdesign-vue-next')['Loading']
  const TSelect: typeof import('tdesign-vue-next')['Select']
  const TSwitch: typeof import('tdesign-vue-next')['Switch']
  const TTable: typeof import('tdesign-vue-next')['Table']
  const TTag: typeof import('tdesign-vue-next')['Tag']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  const TTransfer: typeof import('tdesign-vue-next')['Transfer']
}