/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DirectoryPickerField: typeof import('./src/components/DirectoryPickerField.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensitiveImage: typeof import('./src/components/SensitiveImage.vue')['default']
    SideMenu: typeof import('./src/components/menu/SideMenu.vue')['default']
    SideMenuNode: typeof import('./src/components/menu/SideMenuNode.vue')['default']
    SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}

// For TSX support
declare global {
  const DirectoryPickerField: typeof import('./src/components/DirectoryPickerField.vue')['default']
  const PageLayout: typeof import('./src/components/PageLayout/PageLayout.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SensitiveImage: typeof import('./src/components/SensitiveImage.vue')['default']
  const SideMenu: typeof import('./src/components/menu/SideMenu.vue')['default']
  const SideMenuNode: typeof import('./src/components/menu/SideMenuNode.vue')['default']
  const SubPageLayout: typeof import('./src/components/PageLayout/SubPageLayout.vue')['default']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDivider: typeof import('tdesign-vue-next')['Divider']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TTable: typeof import('tdesign-vue-next')['Table']
  const TTag: typeof import('tdesign-vue-next')['Tag']
  const TTooltip: typeof import('tdesign-vue-next')['Tooltip']
}